version: '3.7'
services:

  grpcox:
    container_name: grpcox
    image: gusaul/grpcox:latest
    ports:
      - "6969:6969"
    networks:
      - webnet
  
  grcppkg:
    container_name: grcpPkg
    build:
      context: ../grcpPkg/.
      dockerfile: Dockerfile
    volumes:
      - ../grcpPkg:/grcpPkg
    networks:
      - webnet

  model1:
    container_name: model1
    build:
      context: ../model1/.
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment: 
      - RPC_PORT=50051
      - RELOAD_APP_ON_FILE_CHANGE=true
    volumes:
      - ../model1:/app
      - ../grcpPkg:/grcpPkg
    networks:
      - webnet

  # api:
  #   container_name: api
  #   build:
  #     context: ../api/.
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:20002"
  #   volumes:
  #     - ../api:/app
  #     - ../grcpPkg:/grcpPkg
  #   networks:
  #     - webnet

networks:
  webnet:
    driver: bridge