version: '3.7'
services:

  inference-api:
    container_name: inference-api
    build:
      context: ../inference-api/.
      dockerfile: Dockerfile
    environment: 
      - RELOAD_APP_ON_FILE_CHANGE=true
      - API_PORT=3001
      - PUSHER_APP_ID=1238509
      - PUSHER_APP_KEY=adbeaa1d731202934e15
      - PUSHER_APP_SECRET=6d5ed969964e6650f3f0
      - PUSHER_APP_CLUSTER=us3
      - PUSHER_APP_SECURE="1"
    volumes:
      - ../inference-api:/app
      - ../grcp-pkg:/grcp-pkg
    networks:
      - webnet
  
  chrome-extension:
    container_name: chrome-extension
    build:
      context: ../chrome-extension/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: 
      - RELOAD_APP_ON_FILE_CHANGE=true
      - NEXT_PUBLIC_PUSHER_APP_KEY=adbeaa1d731202934e15
      - NEXT_PUBLIC_PUSHER_APP_CLUSTER=us3
      - APP_PORT="3000"
    volumes:
      - ../chrome-extension:/app
    networks:
      - webnet

  grpcox:
    container_name: grpcox
    image: gusaul/grpcox:latest
    ports:
      - "6969:6969"
    networks:
      - webnet
  
  grcp-pkg:
    container_name: grcp-pkg
    build:
      context: ../grcp-pkg/.
      dockerfile: Dockerfile
    volumes:
      - ../grcp-pkg:/grcp-pkg
    networks:
      - webnet

  model1:
    container_name: model1
    build:
      context: ../model1/.
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment: 
      - RPC_PORT=50051
      - RELOAD_APP_ON_FILE_CHANGE=true
    volumes:
      - ../model1:/app
      - ../grcp-pkg:/grcp-pkg
    networks:
      - webnet

networks:
  webnet:
    driver: bridge