version: '3.7'
services:
  
  api:
    container_name: api
    build:
      context: ../api/.
      dockerfile: Dockerfile
    ports:
      - "3001:20002"
    volumes:
      - ../api:/app
      - ../grcpPkg:/grcpPkg
    networks:
      - webnet

networks:
  webnet:
    driver: bridge