version: '3.7'
services:

  model1:
    container_name: model1
    build:
      context: ../model1/.
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment: 
      - RPC_PORT=50051
    volumes:
      - ../model1:/app
      - ../grcpPkg:/grcpPkg
    networks:
      - webnet

  # api:
  #   container_name: api
  #   build:
  #     context: ../api/.
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:20002"
  #   volumes:
  #     - ../api:/app
  #     - ../grcpPkg:/grcpPkg
  #   networks:
  #     - webnet

networks:
  webnet:
    driver: bridge