version: '3.7'
services:
  inference-redis:
    container_name: inference-redis
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - webnet

  inference-api:
    container_name: inference-api
    build:
      context: ../inference-api/.
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment: 
      - RELOAD_APP_ON_FILE_CHANGE=true
      - REDIS_PORT=6379
      - REDIS_HOST=inference-redis
      - FRONT_END_PROTOCOL=http
      - FRONT_END_HOST=localhost
      - FRONT_END_PORT=3000
      - GRPC_PROTO_PATH=/grcp-pkg/grcppkg/protos/server.proto
      - MODEL_1_HOST=model1
      - MODEL_1_PORT=50051
      - MODEL_2_HOST=model2
      - MODEL_2_PORT=50052
      - API_PORT=3001
    volumes:
      - ../inference-api:/app
      - ../grcp-pkg:/grcp-pkg
    networks:
      - webnet
  
  chrome-extension:
    container_name: chrome-extension
    build:
      context: ../chrome-extension/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: 
      - RELOAD_APP_ON_FILE_CHANGE=true
      - NEXT_PUBLIC_SOCKER_IO_PROTOCOL=http
      - NEXT_PUBLIC_SOCKER_IO_HOST=localhost
      - NEXT_PUBLIC_SOCKER_IO_PORT=3001
      - APP_PORT="3000"
    volumes:
      - ../chrome-extension:/app
    networks:
      - webnet

  grpcox:
    container_name: grpcox
    image: gusaul/grpcox:latest
    ports:
      - "6969:6969"
    networks:
      - webnet
  
  grcp-pkg:
    container_name: grcp-pkg
    build:
      context: ../grcp-pkg/.
      dockerfile: Dockerfile
    volumes:
      - ../grcp-pkg:/grcp-pkg
    networks:
      - webnet

  model1:
    container_name: model1
    build:
      context: ../model1/.
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment: 
      - RPC_PORT=50051
      - MODEL_ARTIFACT_DIR=/app/model1/models/OuluCASIA
      - RELOAD_APP_ON_FILE_CHANGE=true
    volumes:
      - ../model1:/app
      - ../grcp-pkg:/grcp-pkg
    networks:
      - webnet
  
  model2:
    container_name: model2
    build:
      context: ../model1/.
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment: 
      - RPC_PORT=50052
      - MODEL_ARTIFACT_DIR=/app/model1/models/CK
      - RELOAD_APP_ON_FILE_CHANGE=true
    volumes:
      - ../model1:/app
      - ../grcp-pkg:/grcp-pkg
    networks:
      - webnet

networks:
  webnet:
    driver: bridge